# Generated by Django 5.0 on 2023-12-13 09:29

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('overview_description', models.TextField(blank=True, null=True)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('os_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum OS')),
                ('os_rec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended OS')),
                ('processor_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Processor')),
                ('processor_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Processor')),
                ('memory_min', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimum Memory')),
                ('memory_rec', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recommended Memory')),
                ('storage_min', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimum Storage')),
                ('storage_rec', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recommended Storage')),
                ('directx_min', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum DirectX')),
                ('directx_rec', models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended DirectX')),
                ('graphics_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Graphics')),
                ('graphics_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Graphics')),
                ('category', models.ManyToManyField(to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('overview_description', models.TextField(blank=True, null=True)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dlcs', to='product.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
