# Generated by Django 5.0 on 2024-01-11 11:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('overview_description', models.TextField(blank=True, null=True)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('year', models.DateField(blank=True, null=True)),
                ('os_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum OS')),
                ('os_rec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended OS')),
                ('processor_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Processor')),
                ('processor_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Processor')),
                ('memory_min', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimum Memory')),
                ('memory_rec', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recommended Memory')),
                ('storage_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum Storage')),
                ('storage_rec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended Storage')),
                ('directx_min', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum DirectX')),
                ('directx_rec', models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended DirectX')),
                ('graphics_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Graphics')),
                ('graphics_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Graphics')),
                ('category', models.ManyToManyField(blank=True, null=True, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('overview_description', models.TextField(blank=True, null=True)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('year', models.DateField(blank=True, null=True)),
                ('os_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum OS')),
                ('os_rec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended OS')),
                ('processor_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Processor')),
                ('processor_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Processor')),
                ('memory_min', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimum Memory')),
                ('memory_rec', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recommended Memory')),
                ('storage_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum Storage')),
                ('storage_rec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended Storage')),
                ('directx_min', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum DirectX')),
                ('directx_rec', models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended DirectX')),
                ('graphics_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Graphics')),
                ('graphics_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Graphics')),
                ('category', models.ManyToManyField(blank=True, null=True, to='product.category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dlcs', to='product.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(max_length=255)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.game')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('dlcs', models.ManyToManyField(blank=True, related_name='dlcs', to='product.dlc')),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='product.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialEditionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('base_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='product.game')),
                ('dlcs', models.ManyToManyField(blank=True, to='product.dlc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
