# Generated by Django 5.0 on 2023-12-15 13:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product.category'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dlc',
            name='directx_min',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum DirectX'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='directx_rec',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended DirectX'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='graphics_min',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Graphics'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='graphics_rec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Graphics'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='memory_min',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimum Memory'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='memory_rec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Recommended Memory'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='os_min',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum OS'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='os_rec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended OS'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='overview_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dlc',
            name='processor_min',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum Processor'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='processor_rec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommended Processor'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='storage_min',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Minimum Storage'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='storage_rec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended Storage'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
