# Generated by Django 5.0 on 2024-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_game_sell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.category'),
        ),
    ]
