# Generated by Django 5.0 on 2023-12-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_dlc_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=110, null=True)),
                ('dlcs', models.ManyToManyField(blank=True, to='product.dlc')),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
