# Generated by Django 5.0 on 2023-12-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_decorator_cost_alter_drink_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorator',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
