# Generated by Django 5.0 on 2024-01-28 12:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_game_cover12x12_game_specialcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover12x12',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image12x12'),
        ),
    ]
