# Generated by Django 5.0 on 2023-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_decorator_cost_alter_drink_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('softdrinks', 'SOFT DRINKS'), ('beer', 'BEER')], default=None, max_length=14, null=True),
        ),
    ]
