# Generated by Django 5.0 on 2024-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_game_logo_alter_game_cover12x12'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
