# Generated by Django 5.0 on 2023-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_drink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('beer', 'BEER'), ('softdrinks', 'SOFT DRINKS')], default=None, max_length=14, null=True),
        ),
    ]
