# Generated by Django 5.0 on 2023-12-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_decorator_price_alter_dlc_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorator',
            name='slug',
        ),
    ]
