# Generated by Django 5.0 on 2023-12-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_decorator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
