# Generated by Django 5.0 on 2023-12-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_image_alter_drink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
