# Generated by Django 5.0 on 2024-02-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_dlc_specialcolor_dlc_video_dlcimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.developer'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.publisher'),
        ),
    ]
