# Generated by Django 5.0 on 2023-12-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_game_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
