# Generated by Django 5.0 on 2023-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorator',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='decorator',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='drink',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
