# Generated by Django 5.0 on 2024-02-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comment'),
        ('product', '0011_alter_dlc_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.comment'),
        ),
    ]
