# Generated by Django 5.0 on 2023-12-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_description_decorator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorator',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
