# Generated by Django 5.0 on 2023-12-14 08:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_decorator_productdecorator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='iamge'),
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='iamge'),
        ),
    ]
