# Generated by Django 5.0 on 2023-12-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='sizes',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
