# Generated by Django 5.0 on 2023-12-14 08:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_dlc_cover_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlc',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='productdecorator',
            name='dlcs',
            field=models.ManyToManyField(blank=True, related_name='dlcs', to='product.dlc'),
        ),
        migrations.AlterField(
            model_name='productdecorator',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='product.game'),
        ),
    ]
