# Generated by Django 5.0 on 2024-01-28 09:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_developer_publisher_game_developer_game_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover12x12',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='game',
            name='specialColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
