# Generated by Django 5.0 on 2024-02-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_dlc_developer_dlc_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlc',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlcs', to='product.game'),
        ),
    ]
