# Generated by Django 5.0 on 2024-06-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_game_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
