# Generated by Django 5.0 on 2024-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='type',
            field=models.CharField(choices=[('game', 'GAME'), ('dlc', 'DLC')], max_length=20),
        ),
    ]
