# Generated by Django 5.0 on 2024-02-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_comment_content_type_comment_object_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
