# Generated by Django 4.2.1 on 2023-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='drinkimage'),
        ),
    ]
