# Generated by Django 4.2.1 on 2023-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Espresso',
        ),
        migrations.DeleteModel(
            name='HouseBlend',
        ),
        migrations.DeleteModel(
            name='Soy',
        ),
        migrations.DeleteModel(
            name='Whip',
        ),
        migrations.AddField(
            model_name='mocha',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
