# Generated by Django 4.2.1 on 2023-10-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_delete_drink_delete_mocha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
