# Generated by Django 5.0 on 2023-12-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_decorator_description_alter_decorator_toppings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='decorator',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='decorator',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Decorator',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
