# Generated by Django 4.1.3 on 2023-12-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_topping_description_remove_drink_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beverage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.drink')),
                ('toppings', models.ManyToManyField(blank=True, related_name='drinks', to='home.topping')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
