# Generated by Django 5.0 on 2023-12-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
